{
 "title": "Minio Hot Cluster Metrics",
 "description": "minio dashboard",
 "tags": [ "object-storage" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(minio_total_disks,instance)"
   },
   {
    "name": "metrics_port",
    "query": "label_values(minio_total_disks,instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Minio is a high performance distributed object storage server, designed for large-scale private cloud infrastructure. For more information, check out the docs.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "content": "<img src=\"https://min.io/resources/img/logo/MINIO_wordmark.png\" style=\"height: 40px;\"></img>\n<p style=\"margin-top: 20px;\"><small>\nMinio is a high performance distributed object storage server, designed for \nlarge-scale private cloud infrastructure. For more information, check out the <a href=\"https://docs.min.io\">docs</a>.\n</small></p>"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Start time of the Minio server",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds)",
     "legendFormat": "Start time of the Minio server"
    }
   ]
  },
  {
   "title": "Data Transmited",
   "type": "graph",
   "description": "Data sent by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_sent_bytes_total{instance=\"$instance:$port\"}[5m])",
     "legendFormat": "Transmited:"
    },
    {},
    {},
    {},
    {}
   ]
  },
  {
   "title": "Data Received",
   "type": "graph",
   "description": "Data received by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_received_bytes_total{instance=\"$instance:$port\"}[5m])",
     "legendFormat": "Received:"
    }
   ]
  },
  {
   "title": "Total In/Out Throughput",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_received_bytes_total{instance=\"$instance:$port\"}[5m])",
     "legendFormat": "Received: "
    },
    {
     "expr": "rate(minio_network_sent_bytes_total{instance=\"$instance:$port\"}[5m])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "Disk Storage Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_disk_storage_used_bytes{instance=\"$instance:$port\"}",
     "legendFormat": "Used Storage:"
    }
   ]
  },
  {
   "title": "Disk Storage Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_disk_storage_available_bytes{instance=\"$instance:$port\"}",
     "legendFormat": "Available Storage: "
    }
   ]
  },
  {
   "title": "HTTP Requests duration/s",
   "type": "graph",
   "description": "The current aggregate time spent servicing all HTTP requests  in seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"GET\",instance=\"$instance:$port\"}[5m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"POST\",instance=\"$instance:$port\"}[5m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"PUT\",instance=\"$instance:$port\"}[5m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"HEAD\",instance=\"$instance:$port\"}[5m])",
     "legendFormat": "HEAD"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"DELETE\",instance=\"$instance:$port\"}[5m])",
     "legendFormat": "DELETE"
    }
   ]
  }
 ]
}